using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace CSharp
{
    public partial class Solution
    {
        public void TestRemovePalindromeSub()
        {
            Console.WriteLine(RemovePalindromeSub("ababa")==1);
            Console.WriteLine(RemovePalindromeSub("abb")==2);
            Console.WriteLine(RemovePalindromeSub("baabb") ==2);
        }
        //You are given a string s consisting only of letters 'a' and 'b'. In a single step you can remove one palindromic subsequence from s.
        //Return the minimum number of steps to make the given string empty.
        //A string is a subsequence of a given string if it is generated by deleting some characters of a given string without changing its order.Note that a subsequence does not necessarily need to be contiguous.
        //A string is called palindrome if is one that reads the same backward as well as forward.

        //1 <= s.length <= 1000
        //s[i] is either 'a' or 'b'.
        public int RemovePalindromeSub(string s)
        {
            Func<string, bool> isPalindrome = x => {
                for (int i = 0; i < x.Length / 2; i++)
                    if (x[i] != x[x.Length - i - 1])
                        return false;
                return true;
            };
            return isPalindrome(s) ? 1 : 2;
        }
    }
}
